version: '3'

services:
  lazer:
    build: .
    image: lazer-dev
    container_name: lazer-dev
    working_dir: /go/src/lazer
    depends_on: 
      - db
    ports:
      - 3500:8080
      - 3600:3600
    volumes:
      - ${PWD}/src:/go/src/lazer
    env_file:
      - .env
    command: ["/wait-for-it.sh", "db:3306", "--", "nodemon", "--config", "/nodemon.json"]

  db:
    image: mysql:5
    container_name: lazer-db
    volumes:
      - ${PWD}/.persisted/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    command: --default-authentication-plugin=mysql_native_password
