version: '3'

services:
  go:
    image: golang:1.13-buster
    container_name: go
    stdin_open: true
    tty: true
    ports:
      - 3500:8080
    volumes:
      - ${PWD}:/go/src/lazer
    command: ['/bin/bash']

  mysql:
    image: mysql:8
    container_name: mysql8
    volumes:
      - ${PWD}/.persisted/mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
